### ISSUE TITLE
Segmentation fault with kallisto bus 10xv1

### ISSUE THREAD

**Issue by astrovsky01** [pachterlab/kallisto#216]
Whenever I run kallisto bus with 10xv1, I'm getting "Segmentation Fault: 11" with no further detail. Any advice?

**Comment by AlexWeinreb** [comment]
Make sure you're not running v0.45.0 [which is known to have this issue](https://github.com/pachterlab/kallisto/issues/199). Also, note there was a mistake in version number around v0.44 or v0.45, so just try to install v0.45.1 or v0.46.0 if in doubt.

**Comment by astrovsky01** [comment]
I'm running 46.0 from the most recent version on bioconda

**Comment by AlexWeinreb** [comment]
Just one more suggestion:

> ```
> [index] number of targets: 865
> [index] number of k-mers: 310,087
> ```

This looks low to me (if I'm not mistaken, it means you only have 865 transcripts in your index).

**Comment by astrovsky01** [comment]
I'm using test files, so it's intentionally small

**Comment by sbooeshaghi** [comment]
Can you post the files so I can test them out to see whats wrong?

**Comment by astrovsky01** [comment]
They're each just several thousand lines from the original test files that you list in the kallistobus tools getting started page.

**Comment by astrovsky01** [comment]
I'm running into segmentation fault 11 again with bustools count on the output files of the example workflow...

**Comment by dburkhardt** [comment]
I am having a similar issue following the instructions from the kb velocity tutorial (https://www.kallistobus.tools/kb_velocity_tutorial.html)

```
kb count -i /data/sai/kallisto_indices/human/index.idx -g /data/sai/kallisto_indices/human/transcripts_to_genes.txt -o /data/lab/dat
asets/Krishnaswamy_2017_Embryoid_Body_Timecourse/kallisto/EBT0_1A -c1 /data/sai/kallisto_indices/human/cdna_transcripts_to_capture.txt -c2 /data/sai/kallisto_indices/human/intron_transcripts_to_capture.txt -x 10xv1 -w /data/sai/ka
llisto_indices/human/10xv1_whitelist.txt -t 1 --lamanno /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_I1_001.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timeco
urse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R1_001.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R2_001.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Ti
mecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_I1_002.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R1_002.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Bod
y_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R3_002.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R3_001.fastq.gz /data/lab/datasets/Krishnaswamy_2017_Embryoid
_Body_Timecourse/bamtofastqs/EBT0_1A/bamtofastq_S1_L001_R2_002.fastq.gz
[2019-12-18 12:30:14,345]    INFO Skipping kallisto bus because output files already exist. Use the --overwrite flag to overwrite.
[2019-12-18 12:30:14,345]    INFO Sorting BUS file /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/kallisto/EBT0_1A/output.bus to tmp/output.s.bus
[2019-12-18 12:30:17,499]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.7/site-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/home/dan/.local/lib/python3.7/site-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/home/dan/.local/lib/python3.7/site-packages/kb_python/count.py", line 689, in count_velocity
    memory=memory
  File "/home/dan/.local/lib/python3.7/site-packages/kb_python/count.py", line 97, in bustools_sort
    run_executable(command)
  File "/home/dan/.local/lib/python3.7/site-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/dan/.local/lib/python3.7/site-packages/kb_python/bins/linux/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 1 -m 4G /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/$
allisto/EBT0_1A/output.bus' died with <Signals.SIGSEGV: 11>.
```

Running just the sort command also fails

``` 
/home/dan/.local/lib/python3.7/site-packages/kb_python/bins/linux/bustools/bustools sort -o tmp/output.s.bus -T tmp -t 1 -m 4G /data/lab/datasets/Krishnaswamy_2017_Embryoid_Body_Timecourse/kallisto/EBT0_1A/outpu$
.bus
Read in 0 BUS records
[1]    48692 segmentation fault (core dumped)   sort -o tmp/output.s.bus -T tmp -t 1 -m 4G
```

I have bustools `v0.39.3` and kallisto `v0.46.1`

**Comment by davisidarta** [comment]
I'm facing the same issue when dealing with 10Xv1 data and using bustools `v0.39.3 `and kallisto `0.46.1`. Has anyone found a workaround? From what I discovered so far, this could be caused by an index mismatch when writing to memory.

 @pmelsted , any chance you could look into this bug? Any help would be very helpful.

Here's my command and output. I'm using data obtained with sra-toolkit fastq-dump.

```
kb count --verbose -i index.idx -g transcripts_to_genes.txt -x 10XV1 -o Sample2_1 -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno --loom SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq
/usr/local/lib/python3.6/dist-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
[2020-02-18 10:06:05,739]   DEBUG Printing verbose output
[2020-02-18 10:06:05,739]   DEBUG Creating tmp directory
[2020-02-18 10:06:05,739]   DEBUG Namespace(c1='cdna_transcripts_to_capture.txt', c2='intron_transcripts_to_capture.txt', command='count', fastqs=['SRR8571786_1.fastq', 'SRR8571786_2.fastq', 'SRR8571786_3.fastq'], filter=None, g='transcripts_to_genes.txt', h5ad=False, i='index.idx', keep_tmp=False, lamanno=True, list=False, loom=True, m='4G', nucleus=False, o='Sample2_1', overwrite=False, t=8, verbose=True, w=None, x='10XV1')
[2020-02-18 10:06:05,740]    INFO Generating BUS file from
[2020-02-18 10:06:05,740]    INFO         SRR8571786_1.fastq
[2020-02-18 10:06:05,740]    INFO         SRR8571786_2.fastq
[2020-02-18 10:06:05,740]    INFO         SRR8571786_3.fastq
[2020-02-18 10:06:05,740]   DEBUG /usr/local/lib/python3.6/dist-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o Sample2_1 -x 10XV1 -t 8 SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq
[2020-02-18 10:08:36,072]   DEBUG 
[2020-02-18 10:08:36,072]   DEBUG [index] k-mer length: 31
[2020-02-18 10:08:36,072]   DEBUG [index] number of targets: 790,418
[2020-02-18 10:08:36,073]   DEBUG [index] number of k-mers: 1,112,132,904
[2020-02-18 10:08:36,073]   DEBUG [index] number of equivalence classes: 5,486,663
[2020-02-18 10:08:36,073]   DEBUG [quant] will process sample 1: SRR8571786_1.fastq
[2020-02-18 10:08:36,073]   DEBUG SRR8571786_2.fastq
[2020-02-18 10:08:36,073]   DEBUG SRR8571786_3.fastq
[2020-02-18 10:08:36,073]   DEBUG [quant] finding pseudoalignments for the reads ...
[2020-02-18 10:08:36,073]   ERROR An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kb_python/main.py", line 483, in main
    COMMAND_TO_FUNCTION[args.command](args)
  File "/usr/local/lib/python3.6/dist-packages/kb_python/main.py", line 135, in parse_count
    nucleus=args.nucleus,
  File "/usr/local/lib/python3.6/dist-packages/kb_python/count.py", line 676, in count_velocity
    fastqs, index_path, technology, out_dir, threads=threads
  File "/usr/local/lib/python3.6/dist-packages/kb_python/count.py", line 65, in kallisto_bus
    run_executable(command)
  File "/usr/local/lib/python3.6/dist-packages/kb_python/utils.py", line 147, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/usr/local/lib/python3.6/dist-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o Sample2_1 -x 10XV1 -t 8 SRR8571786_1.fastq SRR8571786_2.fastq SRR8571786_3.fastq' died with <Signals.SIGSEGV: 11>.
[2020-02-18 10:08:36,082]   DEBUG Removing tmp directory

```

**Comment by summerwaterfall** [comment]
Hi, I had the same issue.
I just changed my fastq directory path from absolute path to relative path (from current directory), and the error was somehow fixed..
