### ISSUE TITLE
'An exception occurred' in mixed species count run

### ISSUE THREAD

**Issue by mliiv** [pachterlab/kallisto#248]
Hi,

Running a mixed species (mouse+human) 10x sample, RNA-seq v3. I am following the mixed species ipynb example: https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/notebooks/kb_species_mixing.ipynb#scrollTo=MbwwzFexHeXs

Also, used this thread for how-to on generating a custom gtf file for my transcripts: #https://github.com/pachterlab/kallisto/issues/155 

The mixed index was generated without errors, with 649 transcripts for mm10 and 1067 transcripts for hg19 (GRCh37). They are custom long non-coding transcripts.

Yet, during the !kb count run, I get an error. 
Command: 
`!kb count -i mixed_index.idx \
-g mixed_t2g.txt -x 10xv3 -o output --h5ad -t 4 \
S1/S1_S1_L001_R1_001.fastq.gz S1/S1_S1_L001_R2_001.fastq.gz \
S1/S1_S1_L002_R1_001.fastq.gz S1/S1_S1_L002_R2_001.fastq.gz `

Output:
`VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from jupyter_client.session import utcnow as now
/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning:

calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

[2020-02-07 12:56:58,717]    INFO Generating BUS file to output from
[2020-02-07 12:56:58,718]    INFO         S1/S1_S1_L001_R1_001.fastq.gz
[2020-02-07 12:56:58,718]    INFO         S1/S1_S1_L001_R2_001.fastq.gz
[2020-02-07 12:56:58,718]    INFO         S1/S1_S1_L002_R1_001.fastq.gz
[2020-02-07 12:56:58,718]    INFO         S1/S1_S1_L002_R2_001.fastq.gz
[2020-02-07 12:56:58,718]    INFO Using index mixed_index.idx
[2020-02-07 13:26:32,107]   ERROR 
[index] k-mer length: 31
[index] number of targets: 0
[index] number of k-mers: 0
[index] number of equivalence classes: 0
[quant] will process sample 1: S1/S1_S1_L001_R1_001.fastq.gz
S1/S1_S1_L001_R2_001.fastq.gz
[quant] will process sample 2: S1/S1_S1_L002_R1_001.fastq.gz
S1/S1_S1_L002_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 637,779,253 reads, 0 reads pseudoaligned
[~warn] no reads pseudoaligned.

An exception occurred
Traceback (most recent call last):
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/main.py", line 687, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/main.py", line 219, in parse_count
    temp_dir=temp_dir
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/count.py", line 781, in count
    fastqs, index_paths[0], technology, out_dir, threads=threads
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/validate.py", line 108, in inner
    results = func(*args, **kwargs)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/count.py", line 82, in kallisto_bus
    run_executable(command)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/utils.py", line 103, in inner
    return func(*args, **kwargs)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/utils.py", line 259, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i mixed_index.idx -o output -x 10xv3 -t 4 S1/S1_S1_L001_R1_001.fastq.gz S1/S1_S1_L001_R2_001.fastq.gz S1/S1_S1_L002_R1_001.fastq.gz S1/S1_S1_L002_R2_001.fastq.gz' returned non-zero exit status 1.
[2020-02-07 13:26:32,108]   ERROR An exception occurred
Traceback (most recent call last):
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/main.py", line 687, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/main.py", line 219, in parse_count
    temp_dir=temp_dir
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/count.py", line 781, in count
    fastqs, index_paths[0], technology, out_dir, threads=threads
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/validate.py", line 108, in inner
    results = func(*args, **kwargs)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/count.py", line 82, in kallisto_bus
    run_executable(command)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/utils.py", line 103, in inner
    return func(*args, **kwargs)
  File "/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/utils.py", line 259, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/miniconda3/envs/sc-analysis3-clone/lib/python3.6/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i mixed_index.idx -o output -x 10xv3 -t 4 S1/S1_S1_L001_R1_001.fastq.gz S1/S1_S1_L001_R2_001.fastq.gz S1/S1_S1_L002_R1_001.fastq.gz S1/S1_S1_L002_R2_001.fastq.gz' returned non-zero exit status 1.
CPU times: user 39.1 s, sys: 8.33 s, total: 47.4 s
Wall time: 31min 32s`

I did not get this error when generating the mixed index from ensembl gtf that accompanies the fasta files but I don't see a reason why my custom gtf would not be ok, at least based on the issue nr 115 it should be fine (it looks exactly as instructed by pmelsted). 
I can not really figure out intuitively what's the problem here. mixed_t2g.txt, mixed_cdna.fa and mixed_index.idx files all seem ok. 

Please let me know if I should also provide my full gtf files or anything else. 
Thanks in advance,
Maria

**Comment by mliiv** [comment]
Update on this issue: double-checked and actually the mixed_index.idx file is empty. Sorry about the confusion. Yet there was no error during index generation. mixed_t2g.txt file has 1795 entries, mixed_cdna.fa has 1716 gene_id entries. Could that be a reason that .idx file was left empty?

**Comment by mliiv** [comment]
Turned out that I had some empty fasta mixed_cdna.fa lines, and these had to be removed/corrected, as discussed here: https://www.biostars.org/p/198616/
It would be pretty nice if there were any notices about such problems so that it would be easier and faster to debug them. But anyway, the `!kb count` is running now so I will close this monologue.
