### ISSUE TITLE
Error: unspliced. bu has no BUS records

### ISSUE THREAD

**Issue by gabriellayi** [pachterlab/kallisto#298]
Hi guys,

I'm trying to pre-process my fastq file to get loom files. I'm working on mouse models, so I followed kallisto to build index for ref, I split the index into 8 parts (-n 8). When I ran pre-processing, I put all the index files on the command but seems it's not working, could you please help me with the issue?

Thank you in advance!

Yi
![Screen Shot 2021-02-25 at 13 00 52](https://user-images.githubusercontent.com/50899584/109216537-80bbe100-7769-11eb-988c-c80adbf23f8f.png)

**Comment by ryansohny** [comment]
Hi, I have the same issue. Have you resolved this problem?

Thank you

**Comment by DiyaVaka** [comment]
I have the same issue. Can you please let me know how you were able to resolve it

kb count --tmp TMP --keep-tmp -i /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.k_idx -g /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.t2g -o cDNA_3_velocity --workflow lamanno -c1 /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.cdna_t2c.txt -c2 /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.intron_t2c.txt -t 10 -x 10XV3 --overwrite --h5ad $(find . -name "*.fastq.gz" | sort) 
[2021-12-29 15:47:41,850]    INFO Using index /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.k_idx to generate BUS file to cDNA_3_velocity from
[2021-12-29 15:47:41,850]    INFO         ./cDNA_3_S3_L002_R1_001.fastq.gz
[2021-12-29 15:47:41,850]    INFO         ./cDNA_3_S3_L002_R2_001.fastq.gz
[2021-12-29 15:47:41,850]    INFO         ./cDNA_3_S3_L003_R1_001.fastq.gz
[2021-12-29 15:47:41,850]    INFO         ./cDNA_3_S3_L003_R2_001.fastq.gz
[2021-12-29 17:06:05,600]    INFO Sorting BUS file cDNA_3_velocity/output.bus to TMP/output.s.bus
[2021-12-29 17:17:00,950]    INFO Whitelist not provided
[2021-12-29 17:17:00,951]    INFO Copying pre-packaged 10XV3 whitelist to cDNA_3_velocity
[2021-12-29 17:17:02,170]    INFO Inspecting BUS file TMP/output.s.bus
[2021-12-29 17:20:25,067]    INFO Correcting BUS records in TMP/output.s.bus to TMP/output.s.c.bus with whitelist cDNA_3_velocity/10xv3_whitelist.txt
[2021-12-29 17:22:40,811]    INFO Sorting BUS file TMP/output.s.c.bus to cDNA_3_velocity/output.unfiltered.bus
[2021-12-29 17:27:18,350]    INFO Capturing records from BUS file cDNA_3_velocity/output.unfiltered.bus to TMP/spliced.bus with capture list /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.intron_t2c.txt
[2021-12-29 17:30:05,125]    INFO Sorting BUS file TMP/spliced.bus to cDNA_3_velocity/spliced.unfiltered.bus
[2021-12-29 17:34:23,802]    INFO Inspecting BUS file cDNA_3_velocity/spliced.unfiltered.bus
[2021-12-29 17:37:21,885]    INFO Generating count matrix cDNA_3_velocity/counts_unfiltered/spliced from BUS file cDNA_3_velocity/spliced.unfiltered.bus
[2021-12-29 17:42:50,252]    INFO Capturing records from BUS file cDNA_3_velocity/output.unfiltered.bus to TMP/unspliced.bus with capture list /home/projects/data/genomes/GRCm38.100/kb/GRCm38.100.cdna_t2c.txt
[2021-12-29 17:43:35,386]   ERROR An exception occurred
Traceback (most recent call last):
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/main.py", line 837, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/main.py", line 197, in parse_count
    count_velocity(
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/count.py", line 1567, in count_velocity
    capture_result = bustools_capture(
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/validate.py", line 124, in inner
    validate(arg)
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/validate.py", line 85, in validate
    VALIDATORS[ext](path)
  File "/usr/local/bin/miniconda3/envs/kallisto/lib/python3.9/site-packages/kb_python/validate.py", line 40, in validate_bus
    raise FileVerificationFailed('{} has no BUS records'.format(path))
kb_python.validate.FileVerificationFailed: TMP/unspliced.bus has no BUS records
