### ISSUE TITLE
libc++abi: terminating with uncaught exception of type std::length_error: vector/ using loompy to make loom file from fastq

### ISSUE THREAD

**Issue by chousiniyade** [pachterlab/kallisto#365]
hello
I am using loompy to make loom file from FASTQ.
The error occurred when I was trying the tutorial PBMC file.
The program just stoped by the step of "number of equivalence classes" and it seems very big number
the next step "libc++abi: terminating with uncaught exception of type std::length_error: vector"

Do anyone know what happened on my program?

What is the exact command that was run?

loompy fromfq 1kPBMC.loom 1kPBMC human_GRCh38_gencode.v31 sample.txt pbmc_1k_v3_S1_L001_R1_001.fastq.gz pbmc_1k_v3_S1_L001_R2_001.fastq.gz pbmc_1k_v3_S1_L002_R1_001.fastq.gz pbmc_1k_v3_S1_L002_R2_001.fastq.gz

macOS Monterey 12.3.1 
iMac 27-inch 2020, Intel Core i9 10 core
memory 128GB
hard disk storage 4T

python 3.8.8
loompy 3.0.7
kb-python 0.27.3
kallisto 0.48.0
bustools 0.42.0

------------------------------------------------
Please copy and paste *VERBOSE* output here.

(base) moleculardiagnosis@Moleculars-iMac PBMC % loompy fromfq 1kPBMC.loom 1kPBMC human_GRCh38_gencode.v31 sample.txt pbmc_1k_v3_S1_L001_R1_001.fastq.gz pbmc_1k_v3_S1_L001_R2_001.fastq.gz pbmc_1k_v3_S1_L002_R1_001.fastq.gz pbmc_1k_v3_S1_L002_R2_001.fastq.gz
Loompy v3.0.7 by Linnarsson Lab 🌸 (http://linnarssonlab.org & http://loompy.org)

2022-11-30 15:11:00,553 - INFO - Using 20 threads.
2022-11-30 15:11:00,553 - INFO - kallisto bus -i human_GRCh38_gencode.v31/gencode.v31.fragments.idx -o /var/folders/1v/51_tg1_d50vbvjjnmlft3sgh0000gn/T/tmpsbcohh05 -x 10xv3 -t 20 pbmc_1k_v3_S1_L001_R1_001.fastq.gz pbmc_1k_v3_S1_L001_R2_001.fastq.gz pbmc_1k_v3_S1_L002_R1_001.fastq.gz pbmc_1k_v3_S1_L002_R2_001.fastq.gz
2022-11-30 15:11:00,561 - INFO - [bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
2022-11-30 15:11:00,573 - INFO - [index] k-mer length: 31
2022-11-30 15:11:00,573 - INFO - [index] number of targets: 845,338
2022-11-30 15:11:00,573 - INFO - [index] number of k-mers: 271,648,279
2022-11-30 15:11:16,868 - INFO - [index] number of equivalence classes: 17,770,711,583,828,217,860
2022-11-30 15:11:16,868 - INFO - libc++abi: terminating with uncaught exception of type std::length_error: vector
Traceback (most recent call last):
  File "/opt/anaconda3/bin/loompy", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/loompy/commands.py", line 34, in fromfq
    create_from_fastq(loomfile, sampleid, list(fastqs), indexdir, metadatafile, threads)
  File "/opt/anaconda3/lib/python3.8/site-packages/loompy/bus_file.py", line 418, in create_from_fastq
    for line in execute(cmd, synchronous):
  File "/opt/anaconda3/lib/python3.8/site-packages/loompy/bus_file.py", line 365, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['kallisto', 'bus', '-i', 'human_GRCh38_gencode.v31/gencode.v31.fragments.idx', '-o', '/var/folders/1v/51_tg1_d50vbvjjnmlft3sgh0000gn/T/tmpsbcohh05', '-x', '10xv3', '-t', '20', 'pbmc_1k_v3_S1_L001_R1_001.fastq.gz', 'pbmc_1k_v3_S1_L001_R2_001.fastq.gz', 'pbmc_1k_v3_S1_L002_R1_001.fastq.gz', 'pbmc_1k_v3_S1_L002_R2_001.fastq.gz']' died with <Signals.SIGABRT: 6>.

**Comment by pmelsted** [comment]
It looks like the index file is corrupt. Not sure if this is a kallisto issue or not. Can you run `kallisto inspect` on the index file `human_GRCh38_gencode.v31/gencode.v31.fragments.idx` and tell me how it was generated.

You might also regenerate the index file directly using ```kallisto index``` on the corresponding FASTA file.

**Comment by chousiniyade** [comment]
hi pmelsted
Thank you very much for giving me this idea. 
I am trying to remake an index file again using kallisto index.
