### ISSUE TITLE
Is it possible to create a pseudobam file with kallistobustools (kb)? 

### ISSUE THREAD

**Issue by aalajamii** [pachterlab/kallisto#375]
Hello again, 

I am running kallistobustools (`kb`) on BDWTA dataset (mainly, `kb ref` and `kb count`). I was wondering if it is possible to obtain a pseudobam file similar to the one obtained by `kallisto quant --pseudobam`? Thanks!

**Comment by Yenaled** [comment]
We do have a --genomebam in the devel version of kb that's fully functional (and it will be added into the next stable release of kb).

See https://github.com/pachterlab/kb_python/pull/184

**Comment by aalajamii** [comment]
Perfect, I will have a look. Thanks @Yenaled!

**Comment by aalajamii** [comment]
Hi @Yenaled,

So I have been playing with the devel version of `kb`. 

Running `kb` on a BDWTA dataset works just fine when written like this (without `--genomebam` `--gtf` flags): 
```
kb ref -i index.idx -g t2g.txt -f1 cdna.fa 
Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
Homo_sapiens.GRCh38.108.gtf.gz 
```

```
kb count -i index.idx -g t2g.txt -x BDWTA -w whitelist.txt --verbose
../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz 
../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz 
```

Both `Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz` and `Homo_sapiens.GRCh38.108.gtf.gz` were downloaded from Ensembl.

When I add `--genomebam --gtf Homo_sapiens.GRCh38.108.gtf.gz` to `kb count`, first it takes many hours to run and then prints out the following: 

```
[] DEBUG [main] Printing verbose output
[] DEBUG [main] kallisto binary located at /home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/bins/linux/kallisto/kallisto
[] DEBUG [main] bustools binary located at /home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/bins/linux/bustools/bustools
[] DEBUG [main] Creating `./tmp` directory
[] DEBUG [main] Namespace(list=False, command='count', tmp=None, keep_tmp=False, verbose=True, i='index.idx', g='t2g.txt', x='BDWTA', o='.', w='whitelist.txt', strand=None, genomebam=True, gtf='Homo_sapiens.GRCh38.108.gtf.gz', chromosomes=None, workflow='standard', em=False, umi_gene=False, mm=False, tcc=False, filter=None, filter_threshold=None, c1=None, c2=None, overwrite=False, dry_run=False, loom=False, h5ad=False, cellranger=False, gene_names=False, report=False, no_inspect=False, kallisto='/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/bins/linux/kallisto/kallisto', bustools='/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/bins/linux/bustools/bustools', no_validate=False, parity=None, fragment_l=None, fragment_s=None, fastqs=['../../../../../..MM_WTA_S1_L001_R1_001.fastq.gz', '../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz'])
[] WARNING [main] `--chromosomes` is recommended when using `--genomebam`
[]    INFO [count] Using index index.idx to generate BUS file to . from
[]    INFO [count]         ../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz
[]    INFO [count]         ../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz
[]   DEBUG [count] kallisto bus -i index.idx -o . -x BDWTA --genomebam -g Homo_sapiens.GRCh38.108.gtf.gz ../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz ../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz
[]   DEBUG [count] 
[]   DEBUG [count] [bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
[]   DEBUG [count] [index] k-mer length: 31
[]   DEBUG [count] [index] number of targets: 252,301
[]   DEBUG [count] [index] number of k-mers: 150,068,442
[]   DEBUG [count] [index] number of equivalence classes: 1,087,375
[]   DEBUG [count] [quant] will process sample 1: ../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz
[]   DEBUG [count] ../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz
[]   DEBUG [count] [quant] finding pseudoalignments for the reads ... done
[]   DEBUG [count] [quant] processed 512,009,520 reads, 394,709,324 reads pseudoaligned
[]   DEBUG [count] [  bam] writing pseudoalignments to BAM format .. done
[]   DEBUG [count] [  bam] sorting BAM files ..
[]   ERROR [count] 
[bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
[index] k-mer length: 31
[index] number of targets: 252,301
[index] number of k-mers: 150,068,442
[index] number of equivalence classes: 1,087,375
[quant] will process sample 1: ../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz
../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 512,009,520 reads, 394,709,324 reads pseudoaligned
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files ..
[]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/main.py", line 1347, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/main.py", line 566, in parse_count
    count(
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/count.py", line 1068, in count
    bus_result = kallisto_bus(
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/validate.py", line 116, in inner
    results = func(*args, **kwargs)
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/count.py", line 171, in kallisto_bus
    run_executable(command)
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/aalajami/anaconda3/lib/python3.9/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o . -x BDWTA --genomebam -g Homo_sapiens.GRCh38.108.gtf.gz ../../../../../../MM_WTA_S1_L001_R1_001.fastq.gz ../../../../../../MM_WTA_S1_L001_R2_001.fastq.gz' died with <Signals.SIGKILL: 9>.
[]   DEBUG [main] Removing `./tmp` directory
```

Any help how to resolve this is appreciated!

**Comment by aalajamii** [comment]
Hi @Yenaled, 

I think I have a problem with the BAM file generated. 

I ran `kb ref` and `kb count` with `Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz` and `Homo_sapiens.GRCh38.108.gtf.gz` - downloaded from Ensembl - on a BDWTA sample with R1 and R2 specified. 

However, the BAM file generated has seemingly weird flags. If I run `samtools view pseudoalignments.bam | awk -F '\t' '{print $2}' | sort | uniq -c | sort -nr`, I get the following: 
```
833123557 272 
832963405 256 
129320471 0 
109541085 4 
24235875 16
```

None of these flags (272, 256, 0, 4, 16) is a paired read. What is it that I could be doing wrong? I can't seem to figure it out just yet...

**Comment by Yenaled** [comment]
BD Rhapsody is single-end (paired-end doesn't mean you have an R1 and R2, it means you have two sequences on a fragment that are sequenced together).

**Comment by aalajamii** [comment]
I swear sometimes my brain stops functioning... 
Sorry and as always, thanks a lot!

**Comment by BDXH-FY24** [comment]
is BD enhanced beads V2 supported by kallisto?

**Comment by Yenaled** [comment]
Everything is technically supported by kallisto if you specify the proper technology string and the list of barcodes.

It’s not built in directly in kallisto, but you can customize the kallisto options fairly easily to make it work. I don’t know the details of the technology so you’ll have to see where the barcodes, UMIs, etc. are in the reads.
