### ISSUE TITLE
Memory overflow with kb_ref

### ISSUE THREAD

**Issue by MartinezRuiz-Carlos** [pachterlab/kallisto#443]
Hi all,
Apologies, I have seen related issues but I cannot seem to make it work. I am running `kb ref` to generate a nac index from RefSeq annotations on Hg19. 
I am running `kb_python` 0.28.2 installed through mamba, which by default uses `kallisto` version 0.50.1. Here is the command I am running
```
kb ref --kallisto=${KALLISTO_PATH} --workflow=nac -i hg19_intron_kb_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -f1 cdna.fasta -f2 nascent.fasta \
    ${REFERENCE_DIR_HG19}/hg19.fa \
    ${REFERENCE_DIR_HG19}/hg19.ncbiRefSeq.gtf
```

This has run for >5 hours and crashed due to memory, even tough I gave it up to 250GB of RAM on a HPC. I checked and it indeed actually used up the memory, see also log below
```
[2024-05-18 18:39:30,471]    INFO [ref_nac] Preparing /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v1/reference/hg19/hg19.fa, /nemo/project/proj-tracerx-lung/t
racerx/_PIPELINE/TRACERx-RNAseq-assets/v1/reference/hg19/hg19.ncbiRefSeq.gtf
[2024-05-18 18:39:47,128]    INFO [ref_nac] Splitting genome /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v1/reference/hg19/hg19.fa into cDNA at /nemo/project/
proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpl1r_mfd1
[2024-05-18 18:40:25,884]    INFO [ref_nac] Creating cDNA transcripts-to-capture at /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp
/tmpn3ykz36k
[2024-05-18 18:40:27,094]    INFO [ref_nac] Splitting genome into unprocessed transcripts at /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpvx570mff
[2024-05-18 19:31:42,013]    INFO [ref_nac] Creating unprocessed transcript transcripts-to-capture at /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmp36caoo31
[2024-05-18 19:41:51,749]    INFO [ref_nac] Concatenating 1 cDNA FASTAs to cdna.fasta
[2024-05-18 19:41:53,182]    INFO [ref_nac] Concatenating 1 cDNA transcripts-to-captures to cdna.txt
[2024-05-18 19:41:53,222]    INFO [ref_nac] Concatenating 1 unprocessed transcript FASTAs to nascent.fasta
[2024-05-18 19:55:24,796]    INFO [ref_nac] Concatenating 1 unprocessed transcript transcripts-to-captures to nascent.txt
[2024-05-18 19:55:24,809]    INFO [ref_nac] Concatenating cDNA and unprocessed transcript FASTAs to /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpp617i8zo
[2024-05-18 20:08:53,901]    INFO [ref_nac] Creating transcript-to-gene mapping at t2g_nac.txt
[2024-05-18 20:18:58,513]    INFO [ref_nac] Indexing /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpp617i8zo to hg19_intron_kb_nac.idx
[2024-05-19 16:05:56,570]   ERROR [ref_nac] 
[build] loading fasta file /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpp617i8zo
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
from 808 target sequences
[build] warning: replaced -207750321 non-ACGUT characters in the input sequence
with pseudorandom nucleotides
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Start computing k-mer cardinality estimations (1/2)
KmerStream::KmerStream(): Finished
CompactedDBG::build(): Estimated number of k-mers occurring at least once: 10777820389
CompactedDBG::build(): Estimated number of minimizer occurring at least once: 2659026071
CompactedDBG::filter(): Processed 140348699252 k-mers in 105664 reads
CompactedDBG::filter(): Found 10788175504 unique k-mers
CompactedDBG::filter(): Number of blocks in Bloom filter is 73676508
CompactedDBG::construct(): Extract approximate unitigs (1/2)
CompactedDBG::construct(): Extract approximate unitigs (2/2)
CompactedDBG::construct(): Closed all input files

CompactedDBG::construct(): Splitting unitigs (1/2)

CompactedDBG::construct(): Splitting unitigs (2/2)
CompactedDBG::construct(): Before split: 43911898 unitigs
CompactedDBG::construct(): After split (1/1): 43911898 unitigs
CompactedDBG::construct(): Unitigs split: 86
CompactedDBG::construct(): Unitigs deleted: 0

CompactedDBG::construct(): Joining unitigs
CompactedDBG::construct(): After join: 37169150 unitigs
CompactedDBG::construct(): Joined 6742757 unitigs
[build] extracting D-list k-mers from "/nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v1/reference/hg19/hg19.fa"
[build] identified 1160815 distinguishing flanking k-mers
[build] building MPHF
[build] creating equivalence classes ...
[2024-05-19 16:05:56,630]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/main.py", line 1618, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/main.py", line 267, in parse_ref
    ref_nac(
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/ref.py", line 1023, in ref_nac
    index_result = kallisto_index(
                   ^^^^^^^^^^^^^^^
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/ref.py", line 291, in kallisto_index
    run_executable(command)
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/camp/home/ruizc/tracerx-lung/tctProjects/ruizc/apps/anaconda/envs/kallisto_indices/lib/python3.12/site-packages/kb_python/bins/linux/kallisto/kal
listo index -i hg19_intron_kb_nac.idx -k 31 -t 8 -d /nemo/project/proj-tracerx-lung/tracerx/_PIPELINE/TRACERx-RNAseq-assets/v1/reference/hg19/hg19.fa /nemo/project/proj-tracerx-lung/trac
erx/_PIPELINE/TRACERx-RNAseq-assets/v2/kallisto/hg19/nac_index/tmp/tmpp617i8zo' died with <Signals.SIGKILL: 9>.
slurmstepd: error: Detected 1 oom-kill event(s) in step 3801511.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

I have also run the same fasta and gtf file using --workflow=standard, and that ran in no time with no issues, so I don't think it is an issue with the input files. Any help would be greatly appreciated, thanks!

**Comment by Yenaled** [comment]
It has to be something wrong with your input files. It's saying "Found 10788175504 unique k-mers" ; the entire human genome doesn't even contain that many nucleotides.
